[project]
name = "amateur-algorithm"
version = "0.1.0"
description = "A project for some algorithm implementations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==2.3.2",
    "pandas==2.3.2",
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
